// This file has been generated by Specta. DO NOT EDIT.

export type TauRpcApiOutputTypes =
  | { proc_name: "new_node"; output_type: NodeInfo }
  | { proc_name: "add_bootstrap_node"; output_type: null }
  | { proc_name: "remove_bootstrap_node"; output_type: null }
  | { proc_name: "bootstrap_nodes_changed"; output_type: null };

export type TauRpcApiInputTypes =
  | { proc_name: "new_node"; input_type: null }
  | { proc_name: "add_bootstrap_node"; input_type: { __taurpc_type: string } }
  | { proc_name: "remove_bootstrap_node"; input_type: { __taurpc_type: string } }
  | { proc_name: "bootstrap_nodes_changed"; input_type: { __taurpc_type: ([string, string])[] } };

export type NodeInfo = { key: string; addr: string; is_bootstrap: boolean };

const ARGS_MAP = {
  "":
    "{\"new_node\":[],\"remove_bootstrap_node\":[\"key\"],\"bootstrap_nodes_changed\":[\"bootstrap_nodes\"],\"add_bootstrap_node\":[\"key\"]}",
};
import { createTauRPCProxy as createProxy } from "taurpc";

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP);

type Router = {
  "": [TauRpcApiInputTypes, TauRpcApiOutputTypes];
};
